server:
  port: 8093

spring:

  application:
    name: business-customer-v1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    defer-datasource-initialization: true #read import.sql file after schema generation by hibernate

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:customers_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

#SPRINGDOC
##swagger-ui default path: http://localhost:8093/swagger-ui/index.html
springdoc:
  swagger-ui:
#    path: /swagger-ui.html #swagger-ui custom path: http://localhost:8093/swagger-ui.html
    enabled: true #disable the swagger-ui in prod environment

#SPRINGFOX
##swagger-ui default path: http://localhost:8093/swagger-ui.html
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

documentation:
  api:
    info:
      description: ''
    examples:
      json-exception: '{"type":"/errors/no-data","title":"The customer does not exist","errorCode":"ERROR1000","details":[]}'