server:
  port: 8093

spring:
  application:
    name: customer-v1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #use ddl-auto to create schema or data.sql, but not both
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    defer-datasource-initialization: true #read data-test.sql file after schema generation by hibernate

  h2:
    console:
      enabled: true
  datasource:
    data: classpath:data-test.sql
    url: jdbc:h2:mem:customers_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
